version: '3'
services:
  nifi:
    image: apache/nifi:latest
    container_name: nifi
    restart: always

    ports:
      # HTTP
      - 9595:9595
    environment:
      NIFI_WEB_HTTP_PORT: 9595

    networks:
      - backend
networks:
  backend:
    external:
      name: proxy
